name: CD

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-and-push-docker-image:
    name: Build & Push Docker Image
    uses: strongishllama/github-actions/.github/workflows/docker-build-and-push-image.yaml@main
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
