name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: Lint
    uses: strongishllama/github-actions/.github/workflows/golang-lint.yaml@main
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: strongishllama/golang-action-docker:latest
  generate-readme:
    needs:
      - lint
      - test
    name: Generate Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Generate Readme
        run: |
          curl -Lo ./gha-docs.tar.gz https://github.com/matty-rose/gha-docs/releases/download/v0.15.2/gha-docs-v0.15.2-linux-amd64.tar.gz
          tar -xzf gha-docs.tar.gz gha-docs
          chmod +x gha-docs
          ./gha-docs generate -o README.md action.yaml
      - name: Commit Readme
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "docs: automated update of README.md"
          commit_user_name: GitHub Actions
          commit_user_email: github-actions@millhouse.dev
          file_pattern: README.md
  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - generate-readme
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Install AutoTag
        run: curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin
      - name: Create Tag
        run: |
          git tag $(autotag -n)
          git push --tags
      - name: Create Release
        run: |
          if [[ v$(autotag -n) == *"v0."* ]]; then
            gh release create v$(autotag -n) --generate-notes --prerelease
          else
            gh release create v$(autotag -n) --generate-notes
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
